[workspace]

members = [
    "01-euler1d-nodeps",
    "02-euler1d-ndarray",
    "03-euler1d-locimport",
    "04-euler1d-plm",
    "lib-euler1d",
    ]

[profile.release]
lto = true # enabling link-time optimizations on the release build really improves performance
