[package]
name = "euler1d-locimport"
version = "0.1.0"
authors = ["Jonathan Zrake <jonathan.zrake@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = "0.13.1"
lib-euler1d = { path = "../lib-euler1d" }
